using System.Collections.Frozen;
using System.Collections.ObjectModel;
using System.Reflection;
using System.Xml;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;

namespace codecrush.gstreamer.source_generator;

internal record DllMapRecord(string Source, string Target, string Os);

[Generator]
public sealed class DllMapperGenerator : IIncrementalGenerator
{
    private static AssemblyName AssemblyName = typeof(DllMapperGenerator).Assembly.GetName();
    private static string GeneratedCodeAttribute = $@"global::System.CodeDom.Compiler.GeneratedCode(""{AssemblyName.Name}"", ""{AssemblyName.Version}"")";
        
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
            
        var redirectDll = context.AdditionalTextsProvider
                .Where(a => a.Path.EndsWith("gstreamer-sharp.dll.config"))
                .Select((a, ct) => a.GetText(ct))
                .Where(t => t is not null)
                .SelectMany((t, ct) =>
                {
                    var xml = XDocument.Parse(t!.ToString(),LoadOptions.None);
                    return xml
                        .Element("configuration")?
                        .Elements("dllmap")
                        .Select(e => new DllMapRecord(
                            e.Attribute("dll")?.Value ?? string.Empty,
                            e.Attribute("target")?.Value ?? string.Empty, 
                            e.Attribute("os")?.Value ?? string.Empty
                            )) ?? [];
                })
                .Collect()
            ;
            
            
        context.RegisterSourceOutput(redirectDll, static (sp, records) =>
        {
            var osEnum = GenerateEnum(records.Select(r => r.Os).Prepend("Windows"));
            sp.AddSource("OsEnum.g.cs", osEnum);
            sp.AddSource("DllMap.g.cs", GenerateMapClass(records));
        });
    }

    private static string GenerateEnum(IEnumerable<string> os)
    {
        // lang=c#
        var enumClass = $$"""
                        // <auto-generated />
                         namespace CodeCrush.GStreamer.SourceGenerator;
                         
                         [{{GeneratedCodeAttribute}}]
                         public enum OsEnum
                         {
                            {{os
                                .Select(o => o.ToUpper())
                                .Distinct()
                                .Aggregate((acc, o) => $"{acc},{o}")}}
                         }
                        """;

        return enumClass;
    }

    private static string GenerateMapClass(IReadOnlyCollection<DllMapRecord> records)
    {
        
        var groups = records.GroupBy(r => r.Os);

        var llFunc = new LinkedList<string>();
        var llOs = new LinkedList<string>();
        
        foreach (var g in groups)
        {
            // lang=c#
            var func = $$"""
                          private static string GetDllTarget{{g.Key}}(global::System.String dllName)
                          {
                              return dllName switch 
                              {
                                 {{g.Aggregate("_ => dllName",
                                      (acc, e) => 
                                          $"\"{e.Target}\" => \"{e.Target}\",\n\t\t{acc}")
                                 }}
                              };
                          }
                         """;
            llOs.AddLast(g.Key);
            llFunc.AddLast(func);
        }

        
        // lang=c#
        var classDefinition = $$"""
                    // <auto-generated />
                    namespace CodeCrush.GStreamer.SourceGenerator;
                    [{{GeneratedCodeAttribute}}]
                    public static class DllMap
                    {
                        public static string GetDllTarget(global::CodeCrush.GStreamer.SourceGenerator.OsEnum os, global::System.String dllName)
                        {
                            return os switch 
                            {
                                {{llOs
                                    .Aggregate("_ => \"dllName\"",(acc, e) => 
                                        $"global::CodeCrush.GStreamer.SourceGenerator.OsEnum.{e.ToUpper()} => GetDllTarget{e}(dllName),\n\t\t\t{acc}")}}
                                ,
                            };
                        }
                        {{llFunc.Aggregate((acc, e) => $"{acc}\n{e}")}}
                    }
                    """;
        
        return classDefinition;
    }
}
